name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Sync files
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github" --exclude=".gitignore" --exclude="frontend" --exclude="venv" --exclude="secret.yaml" --include="" --filter=""
        path: /
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.REMOTE_PORT }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
